[ODE] #Wb2-854 Intégration des features du RepositoryEvent dans l'EUR
OPEN-ENT-NG/exercizer pull request #24
Opened 2023-08-03 16:54 UTC by nabil-mansouri

# Description 

Cette évolution implémente le branchement des fonctions suivantes des RepositoryEvent dans l'EUR:

- suppression d'une liste de groupe (transition d'année)
- suppression d'une liste d'utilisateurs (transition d'année)
- importation d'une ressource

# Tests

Il y a les test automatisés suivant:

- importation d'une ressource => indexation dans OpenSearch
- partage de la ressource importée à un groupe => Mise à jour  des partages dans OpenSearch
- suppression du groupe (simule la transition d'année) => le RepositoryEvent ne fait rien sur les subject(uniquement les subjectscheduled et les subjectcopy qui sont modifiés) => La donnée n'est pas modifié dans opensearch
- partage de la ressource importée à un user => Mise à jour des partages dans OpenSearch
- suppression du user (simule la transition d'année) => le RepositoryEvent ne fait rien sur les subject(uniquement les subjectscheduled et les subjectcopy qui sont modifiés) => La donnée n'est pas modifié dans opensearch
- suppression du owner de la ressource importée (simule la transition d'année) => Le RepositoryEvent met deleted=true à jour => le champs trashed=true est mis à jour dans OpenSearch

2023-08-04 15:17 UTC, juniorode requested changes

2023-08-04 15:17 UTC, juniorode commented on src/main/java/fr/openent/exercizer/events/ExercizerRepositoryEvents.java
> +                                .put("newIds", idsByTable);
Même commentaire que sur entcore pour le nouveau champ `newIds`

2023-08-07 12:25 UTC, nabil-mansouri commented on src/main/java/fr/openent/exercizer/events/ExercizerRepositoryEvents.java
> +                                .put("newIds", idsByTable);
en rediscutant avec @mariusode , on se disait que plutôt fix le code exxistant, il faudrait plutôt envisager un refacto du repositoryevent qui peut être parfois compliqué à maintenir/faire évoluer

2023-08-07 14:32 UTC, mariusode approved these changes

2023-08-07 15:59 UTC, merged